### ISSUE TITLE
Support Multiple UPSses

### ISSUE THREAD

**Issue by rafaelreis-r** [masterwishx/NUT-UPS-InfluxDBv2#4]
Hey, 

Very cool dash. I was wondering how to configure the dashboard to support multiple UPSses monitored by NUT. I have 2 UPSes and it only sees the first one. 

Thanks

**Comment by masterwishx** [comment]
> Hey,
> 
> Very cool dash. I was wondering how to configure the dashboard to support multiple UPSses monitored by NUT. I have 2 UPSes and it only sees the first one.
> 
> Thanks

i will upload the new version with multi bucket support today later here and in grafana ...

**Comment by rafaelreis-r** [comment]
Thanks!

But I don’t think it is a bucket configuration. Telegraf scrapes both upses
from NUT and sends to the same infludbv2 bucket.

Having separate buckets would involve setting up 2 telegraf instances
wouldn’t it?


Em ter., 28 de mai. de 2024 às 13:37, DaRK AnGeL ***@***.***>
escreveu:

**Comment by masterwishx** [comment]
> But I don’t think it is a bucket configuration. Telegraf scrapes both upses from NUT and sends to the same infludbv2 bucket.

i made only support for multi bucket at now .  only one can be visible at same time 

![image](https://github.com/masterwishx/NUT-UPS-InfluxDBv2/assets/28630321/04895bbb-5c9a-42bd-85a7-a56db89932e2)
![image](https://github.com/masterwishx/NUT-UPS-InfluxDBv2/assets/28630321/3da94e71-9bd0-417d-9ae2-cbd1ce683c56)


> Having separate buckets would involve setting up 2 telegraf instances wouldn’t it?

No , you can send from second ups to second bucket

**Comment by masterwishx** [comment]
> Having separate buckets would involve setting up 2 telegraf instances wouldn’t it?

you need to change telegraf config for send data to two buckets from two ups , i have only one :)
