### ISSUE TITLE
additional_fields not being used

### ISSUE THREAD

**Issue by moogoos** [masterwishx/NUT-UPS-InfluxDBv2#6]
I get an error when I enable additional_fields * that the fields aren't being used the it fails to start

**Comment by masterwishx** [comment]
> I get an error when I enable additional_fields * that the fields aren't being used the it fails to start

What versions of telegraf and nut? What logs of telegraf says?

**Comment by moogoos** [comment]
TELEGRAF_VERSION=1.25.3
upscmd 2.8.2

```
[[inputs.upsd]]
   server = "host"
   port = 3493
   additional_fields = ["*"]
```

plugin inputs.upsd: line 1: configuration specified the fields ["additional_fields"], but they weren't used

**Comment by masterwishx** [comment]
> TELEGRAF_VERSION=1.25.3 upscmd 2.8.2
> 
> ```
> [[inputs.upsd]]
>    server = "host"
>    port = 3493
>    additional_fields = ["*"]
> ```
> 
> plugin inputs.upsd: line 1: configuration specified the fields ["additional_fields"], but they weren't used

From telegraf config :  

```
  ## Collect additional fields if they are available for the UPS
  ## The fields need to be specified as NUT variable names, see
  ## https://networkupstools.org/docs/developer-guide.chunked/apas02.html
  ## Wildcards are accepted.
  # additional_fields = []
```

Try comment this part and check if you have all values. 
it seems you dont have `additional_fields` ?!

**Comment by moogoos** [comment]
how do I know if I have all fields though?

It's running without it or I should say the container starts, but the dashboard doesn't load all the panels correctly. It's a Eaton 5PX1500RT

![Screenshot 2024-11-09 at 11 47 38 PM](https://github.com/user-attachments/assets/236a6f85-6205-4811-862d-9017607a8fa8)

**Comment by masterwishx** [comment]
> how do I know if I have all fields though?

you should check all values you have by :  `upsc MYUPSname` 
Then you should check influxdbv2 what you have in bucket

**Comment by moogoos** [comment]
ok will have a look

**Comment by masterwishx** [comment]
> ok will have a look

Also you have old telegraf version , latest 1.32.2.
Also some values from nut like (input transfer bypass etc was added by me in pr to nut main version) that not released yet but can be compiled , but you dont need it if your ups is not online

**Comment by masterwishx** [comment]
> ok will have a look

I committed to telegraf also to have more values, so please check lasted version of telegraf with additional fields

**Comment by moogoos** [comment]
Nice. Upgraded to 1.32.2 and the error is gone.
